language: rust

cache: cargo

rust:
  - stable
  - nightly

env:
  - CRATE=boards/samc21n_xplained_pro EXAMPLES="--example=blinky_basic --example=blinky_rtfm"
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - rustup target add thumbv6m-none-eabi

script:
  - "cd $CRATE"
  - "cargo build ${EXAMPLES:---examples} $FEATURES"

stages:
  - test
